---
scrape_configs:
- job_name: elasticsearch
  scrape_interval: 60s
  scrape_timeout:  30s
  metrics_path: "/metrics"
  static_configs:
  - targets:
    - elasticsearch_exporter:9108
    labels:
      service: elasticsearch
  relabel_configs:
  - source_labels: [__address__]
    regex: '(.*)\:9108'
    target_label:  'instance'
    replacement:   '$1'
  - source_labels: [__address__]
    regex:         '.*\.(.*)\.lan.*'
    target_label:  'environment'
    replacement:   '$1'

